# Generated by Django 6.0.5 on 2026-06-02 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_level', models.CharField(default='12', max_length=20)),
                ('primary_interest', models.CharField(choices=[('anime', 'Anime'), ('cricket', 'Cricket'), ('gaming', 'Gaming'), ('movies', 'Movies'), ('real_life', 'Real Life'), ('textbook', 'Textbook Style')], default='real_life', max_length=30)),
                ('explanation_style', models.CharField(choices=[('simple', 'Simple'), ('story_based', 'Story Based'), ('exam_focused', 'Exam Focused'), ('visual', 'Visual'), ('step_by_step', 'Step By Step')], default='step_by_step', max_length=30)),
                ('learning_goal', models.CharField(blank=True, default='Improve weak concepts through personalized revision.', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
