# Generated by Django 6.0.5 on 2026-06-03 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(blank=True, max_length=50)),
                ('favorite_contexts', models.JSONField(blank=True, default=list)),
                ('preferred_style', models.CharField(choices=[('visual', 'Visual'), ('story', 'Story Based'), ('analogy', 'Analogy Based'), ('step_by_step', 'Step by Step'), ('practice_first', 'Practice First')], default='step_by_step', max_length=30)),
                ('weak_subjects', models.JSONField(blank=True, default=list)),
                ('weak_topics', models.JSONField(blank=True, default=list)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learning_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
