# Generated by Django 6.0.5 on 2026-06-03 07:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalization', '0002_learningprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentprofile',
            options={'verbose_name': 'Student Profile', 'verbose_name_plural': 'Student Profiles'},
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='class_level',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='explanation_style',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='learning_goal',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='primary_interest',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='current_streak',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='daily_goal_minutes',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='grade_level',
            field=models.CharField(default='General', max_length=50),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='interests',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='last_active_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='learning_style',
            field=models.CharField(choices=[('simple', 'Simple'), ('visual', 'Visual'), ('story', 'Story Based'), ('example', 'Example Based'), ('practice', 'Practice Based')], default='simple', max_length=30),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='longest_streak',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='preferred_explanation_length',
            field=models.CharField(default='medium', help_text='short, medium, or detailed', max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='preferred_subjects',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='weak_subjects',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='StudentStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('activity_type', models.CharField(default='learning_activity', max_length=100)),
                ('points', models.PositiveIntegerField(default=10)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streak_logs', to='personalization.studentprofile')),
            ],
            options={
                'verbose_name': 'Student Streak',
                'verbose_name_plural': 'Student Streaks',
                'ordering': ['-date', '-created_at'],
                'unique_together': {('profile', 'date', 'activity_type')},
            },
        ),
        migrations.DeleteModel(
            name='LearningProfile',
        ),
    ]
