# Generated by Django 6.0.5 on 2026-06-08 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0001_initial'),
        ('tests_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attempt',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='attempt',
            old_name='submitted_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='attempt',
            old_name='total_score',
            new_name='obtained_marks',
        ),
        migrations.CreateModel(
            name='AttemptAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_answer', models.TextField(blank=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('marks_awarded', models.FloatField(default=0)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='attempts.attempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_answers', to='tests_app.question')),
            ],
        ),
        migrations.CreateModel(
            name='Mistake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weak_concept', models.CharField(blank=True, max_length=255)),
                ('mistake_type', models.CharField(blank=True, max_length=100)),
                ('explanation', models.TextField(blank=True)),
                ('personalized_explanation', models.TextField(blank=True)),
                ('revision_task', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mistakes', to='attempts.attempt')),
                ('attempt_answer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mistake', to='attempts.attemptanswer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mistakes', to='tests_app.question')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='AnswerAttempt',
        ),
    ]
