# Generated by Django 6.0.5 on 2026-06-02 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tests_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassReportSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_attempts', models.PositiveIntegerField(default=0)),
                ('average_score', models.FloatField(default=0)),
                ('average_percentage', models.FloatField(default=0)),
                ('most_common_weak_concept', models.CharField(blank=True, max_length=255)),
                ('most_common_mistake_type', models.CharField(blank=True, max_length=100)),
                ('suggested_teacher_action', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('test', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report_snapshot', to='tests_app.test')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='RemedialGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=255)),
                ('mistake_type', models.CharField(max_length=100)),
                ('weak_concept', models.CharField(max_length=255)),
                ('suggested_action', models.TextField()),
                ('student_count', models.PositiveIntegerField(default=0)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remedial_groups', to='tests_app.test')),
            ],
            options={
                'ordering': ['-student_count', 'group_name'],
                'unique_together': {('test', 'mistake_type', 'weak_concept')},
            },
        ),
    ]
